# Configuration for typegen


# web handlers dir
handler = "handlers.go"

# sqlstore dir
sql = "sqlstore.go"

# go types dir
type = "ty.go"

# migrations dir
migration = "migrations.sql"


# ui dir
ui = "ui.ts"

# base dir
base-dir = "example"

# schema
schema = "schema.go"
